package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.util.ArrayList;
import napakalaki.BadConsequence;
import napakalaki.TreasureKind;

/**
 *
 * @author Rafa
 */
public class BadConsequenceView extends javax.swing.JPanel {
    private BadConsequence badModel;
    /*
    private final String text;
    private final int levels;
    private int nVisibleTreasures;
    private int nHiddenTreasures;
    private boolean death;
    private ArrayList<TreasureKind> specificHiddenTreasures;
    private ArrayList<TreasureKind> specificVisibleTreasures;
    */
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    public void SetBadConsequence(BadConsequence bad){
        badModel = bad;
        
        text.setText(badModel.getText());
        levels.setText(Integer.toString(badModel.getLevels()));
        String mensajeMuerte;
        if(badModel.kills())
            mensajeMuerte = "Si";
        else
            mensajeMuerte = "No";
        death.setText(mensajeMuerte);
        
        //getMaxTreasureLost() Mejora de diseño, así no hay que poner 999
        if(badModel.getnVisibleTreasures()==BadConsequence.getMaxTreasureLost()){
            nVisibleTreasures.setText("Todos");
        }
        else
            nVisibleTreasures.setText(Integer.toString(badModel.getnVisibleTreasures()));
        
        if(badModel.getnHiddenTreasures()==BadConsequence.getMaxTreasureLost()){
            nHiddenTreasures.setText("Todos");
        }
        else
            nHiddenTreasures.setText(Integer.toString(badModel.getnHiddenTreasures()));
        
        specificHiddenTreasures.setText(badModel.getSpecificHiddenTreasures().toString());
        specificVisibleTreasures.setText(badModel.getSpecificVisibleTreasures().toString());
        
        repaint();
    }
    
    public void setNull(){
        text.setText("");
        levels.setText("Niveles");
        death.setText("Muerte");
        nVisibleTreasures.setText("Número de Tesoros Visibles");
        nHiddenTreasures.setText("Número de Tesoros Ocultos");
        specificHiddenTreasures.setText("Tesoros Ocultos");
        specificVisibleTreasures.setText("Tesoros Visibles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();
        levels = new javax.swing.JTextField();
        death = new javax.swing.JTextField();
        deathLabel = new javax.swing.JLabel();
        nVisibleTreasures = new javax.swing.JTextField();
        nVisibleLabel = new javax.swing.JLabel();
        nHiddenLabel = new javax.swing.JLabel();
        nHiddenTreasures = new javax.swing.JTextField();
        specificVisibleTreasures = new javax.swing.JTextField();
        specificHiddenTreasures = new javax.swing.JTextField();
        specificVisibleLabel = new javax.swing.JLabel();
        specificHiddenLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo"));
        setToolTipText("");

        textLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        textLabel.setText("Descripcion");
        textLabel.setToolTipText("");

        levelsLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        levelsLabel.setText("Niveles Perdidos");
        levelsLabel.setToolTipText("");

        levels.setEditable(false);
        levels.setText("niveles");

        death.setEditable(false);
        death.setText("muerte");
        death.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathActionPerformed(evt);
            }
        });

        deathLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        deathLabel.setText("¿Te Mata?");
        deathLabel.setToolTipText("");

        nVisibleTreasures.setEditable(false);
        nVisibleTreasures.setText("nVisible");
        nVisibleTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisibleTreasuresActionPerformed(evt);
            }
        });

        nVisibleLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        nVisibleLabel.setText("Tesoros Visibles");
        nVisibleLabel.setToolTipText("");

        nHiddenLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        nHiddenLabel.setText("Tesoros Ocultos");
        nHiddenLabel.setToolTipText("");

        nHiddenTreasures.setEditable(false);
        nHiddenTreasures.setText("nVisible");

        specificVisibleTreasures.setEditable(false);
        specificVisibleTreasures.setText("specificVisibleTreasures");

        specificHiddenTreasures.setEditable(false);
        specificHiddenTreasures.setText("specificHiddenTreasures");

        specificVisibleLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        specificVisibleLabel.setText("Tipos de Tesoros Visibles");
        specificVisibleLabel.setToolTipText("");

        specificHiddenLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        specificHiddenLabel.setText("Tipos de Tesoros Ocultos");
        specificHiddenLabel.setToolTipText("");

        text.setEditable(false);
        text.setColumns(1);
        text.setLineWrap(true);
        text.setRows(3);
        text.setTabSize(2);
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specificVisibleLabel)
                            .addComponent(specificHiddenLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(specificHiddenTreasures, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelsLabel)
                                    .addComponent(deathLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(death, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levels, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nVisibleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nHiddenLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(nVisibleTreasures)))
                            .addComponent(specificVisibleTreasures, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(textLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelsLabel)
                    .addComponent(levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nVisibleLabel)
                    .addComponent(nVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deathLabel)
                    .addComponent(death, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nHiddenLabel)
                    .addComponent(nHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(specificVisibleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificHiddenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deathActionPerformed

    private void nVisibleTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisibleTreasuresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisibleTreasuresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField death;
    private javax.swing.JLabel deathLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField levels;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JLabel nHiddenLabel;
    private javax.swing.JTextField nHiddenTreasures;
    private javax.swing.JLabel nVisibleLabel;
    private javax.swing.JTextField nVisibleTreasures;
    private javax.swing.JLabel specificHiddenLabel;
    private javax.swing.JTextField specificHiddenTreasures;
    private javax.swing.JLabel specificVisibleLabel;
    private javax.swing.JTextField specificVisibleTreasures;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
