/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.Cultist;

/**
 *
 
 */
public class CultistView extends javax.swing.JPanel {
    private Cultist cultistModel;
    /**
     * Creates new form CultistView
     */
    public CultistView() {
        initComponents();
    }

    public void setCultist(Cultist c){
        cultistModel = c;
        name.setText(cultistModel.getName());
        gainedLevels.setText(Integer.toString(cultistModel.getGainedLevels()));
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelGainedLevels = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gainedLevels = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Carta Sectario"));
        setForeground(new java.awt.Color(255, 204, 204));

        labelName.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        labelName.setText("Nombre");

        labelGainedLevels.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        labelGainedLevels.setText("Niveles Ganados");

        name.setEditable(false);
        name.setText("Nombre");

        gainedLevels.setEditable(false);
        gainedLevels.setText("Niveles que ganas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGainedLevels)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gainedLevels)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGainedLevels)
                    .addComponent(gainedLevels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gainedLevels;
    private javax.swing.JLabel labelGainedLevels;
    private javax.swing.JLabel labelName;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
