/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import javax.swing.JButton;
import napakalaki.CombatResult;
import napakalaki.Napakalaki;
/**
 *
 * 
 */
public class NapakalakiView extends javax.swing.JFrame {
    private Napakalaki napakalakiModel;    
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }
    public void setNapakalaki(Napakalaki napakalaki){
        napakalakiModel = napakalaki;
        currentMonsterView.setNull();
        currentPlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
        currentPlayerView.setNapakalaki(napakalaki);
        currentPlayerView.getButtonDiscardTreasures().setEnabled(false);
        buttonNextTurn.setEnabled(false);
        buttonCombat.setEnabled(false);
        repaint();
    }

    public JButton getButtonNextTurn() {
        return buttonNextTurn;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combatResultLabel = new javax.swing.JLabel();
        combatResult = new javax.swing.JTextField();
        mensajeLabel = new javax.swing.JLabel();
        mensaje = new javax.swing.JTextField();
        buttonNextTurn = new javax.swing.JButton();
        buttonCombat = new javax.swing.JButton();
        currentMonsterView = new GUI.MonsterView();
        currentPlayerView = new GUI.PlayerView();
        showMonster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 211));

        combatResultLabel.setText("Resultado del Combate");

        combatResult.setEditable(false);
        combatResult.setText("Resultado");

        mensajeLabel.setText("Otros Mensajes");

        mensaje.setEditable(false);
        mensaje.setText(" ");

        buttonNextTurn.setText("Siguente Turno");
        buttonNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextTurnActionPerformed(evt);
            }
        });

        buttonCombat.setBackground(new java.awt.Color(255, 0, 51));
        buttonCombat.setText("Combat!");
        buttonCombat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCombatActionPerformed(evt);
            }
        });

        currentPlayerView.setBackground(new java.awt.Color(204, 204, 204));

        showMonster.setText("Mostrar Monstruo");
        showMonster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMonsterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combatResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatResult, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNextTurn)
                .addGap(53, 53, 53)
                .addComponent(mensajeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(currentPlayerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentMonsterView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showMonster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combatResultLabel)
                    .addComponent(combatResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeLabel)
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCombat)
                    .addComponent(buttonNextTurn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentPlayerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentMonsterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showMonster)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextTurnActionPerformed
        napakalakiModel.nextTurn();
        currentPlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
        currentPlayerView.setNapakalaki(napakalakiModel);
        currentPlayerView.getButtonDiscardTreasures().setEnabled(false);
        currentPlayerView.getButtonMakeVisible().setEnabled(true);
        currentPlayerView.getButtonBuyLevels().setEnabled(true);
        buttonCombat.setEnabled(true);
        buttonNextTurn.setEnabled(false);
        buttonCombat.setEnabled(false);    
        showMonster.setEnabled(false);
        combatResult.setText("Resultado");
        currentMonsterView.setNull();  
        showMonster.setEnabled(true);
        mensaje.setText("");
        repaint();
    }//GEN-LAST:event_buttonNextTurnActionPerformed

    private void buttonCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCombatActionPerformed
        CombatResult result = napakalakiModel.combat();
        buttonCombat.setEnabled(false);
        currentPlayerView.getButtonBuyLevels().setEnabled(false);
        if(result == CombatResult.WIN){
            currentPlayerView.getButtonMakeVisible().setEnabled(true);
            buttonNextTurn.setEnabled(true);
        }
        else if (result == CombatResult.WINANDWINGAME){
            mensaje.setText("Has ganado el juego!");
            currentPlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
            EndGame endAlert = new EndGame(this,true);
            endAlert.setVisible(true);
        }
        else{
            if(result == CombatResult.LOSEANDCONVERT){
            currentPlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
            mensaje.setText("Ahora eres Sectario");
            }
            if(!napakalakiModel.nextTurnAllowed()){
                currentPlayerView.getButtonDiscardTreasures().setEnabled(true);
            }
            else{
                currentPlayerView.getButtonMakeVisible().setEnabled(true);
            }
            buttonNextTurn.setEnabled(true);
        }
        
        currentPlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
        combatResult.setText(result.toString());
        repaint();
    }//GEN-LAST:event_buttonCombatActionPerformed

    private void showMonsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMonsterMouseClicked
        currentMonsterView.setMonster(napakalakiModel.getCurrentMonster());
        buttonCombat.setEnabled(true);        
        showMonster.setEnabled(false);
        currentPlayerView.getButtonMakeVisible().setEnabled(false);
        currentPlayerView.getButtonBuyLevels().setEnabled(false);
        repaint();
    }//GEN-LAST:event_showMonsterMouseClicked

    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCombat;
    private javax.swing.JButton buttonNextTurn;
    private javax.swing.JTextField combatResult;
    private javax.swing.JLabel combatResultLabel;
    private GUI.MonsterView currentMonsterView;
    private GUI.PlayerView currentPlayerView;
    private javax.swing.JTextField mensaje;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JButton showMonster;
    // End of variables declaration//GEN-END:variables
}
