package GUI;

import napakalaki.Treasure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class TreasureView extends javax.swing.JPanel {
    private Treasure treasureModel;
    private boolean selected = false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    public boolean isSelected() {
        return selected;
    }

    public Treasure getTreasure() {
        return treasureModel;
    }
    
    
    public void setTreasure(Treasure t){
        treasureModel = t;
        
        name.setText(treasureModel.getName());
        treasureKind.setText(treasureModel.getType().toString());
        minBonus.setText(Integer.toString(treasureModel.getMinBonus()));
        maxBonus.setText(Integer.toString(treasureModel.getMaxBonus()));
        goldCoins.setText(Integer.toString(treasureModel.getGoldCoins()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treasureKind = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        labelMinBonus = new javax.swing.JLabel();
        labelMaxBonus = new javax.swing.JLabel();
        labelGoldCoins = new javax.swing.JLabel();
        labelTreasureKind = new javax.swing.JLabel();
        maxBonus = new javax.swing.JTextField();
        minBonus = new javax.swing.JTextField();
        goldCoins = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setForeground(new java.awt.Color(219, 196, 149));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        treasureKind.setEditable(false);
        treasureKind.setText("Tipo de Tesoro");

        name.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        name.setText("Nombre");

        labelMinBonus.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labelMinBonus.setText("Bonus Mínimo");

        labelMaxBonus.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labelMaxBonus.setText("Bonus Máximo");

        labelGoldCoins.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labelGoldCoins.setText("Piezas de Oro");

        labelTreasureKind.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labelTreasureKind.setText("Tipo");

        maxBonus.setEditable(false);
        maxBonus.setText("Bonus Max");

        minBonus.setEditable(false);
        minBonus.setText("Bonus Min");

        goldCoins.setEditable(false);
        goldCoins.setText("GoldCoins");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelGoldCoins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goldCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMinBonus)
                                    .addComponent(labelMaxBonus))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(minBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(maxBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTreasureKind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(treasureKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaxBonus)
                    .addComponent(maxBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinBonus)
                    .addComponent(minBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goldCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGoldCoins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTreasureKind)
                    .addComponent(treasureKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(selected==true){
            selected = false;
            setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        }
        else{
            selected = true;
            setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 4, true));
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField goldCoins;
    private javax.swing.JLabel labelGoldCoins;
    private javax.swing.JLabel labelMaxBonus;
    private javax.swing.JLabel labelMinBonus;
    private javax.swing.JLabel labelTreasureKind;
    private javax.swing.JTextField maxBonus;
    private javax.swing.JTextField minBonus;
    private javax.swing.JLabel name;
    private javax.swing.JTextField treasureKind;
    // End of variables declaration//GEN-END:variables
}
